title: Denis Kazakov 
# overwrite https://aregsar.com/blog/2019/how-to-customize-your-github-pages-blog-layout-in-five-minutes/
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an experienced data scientist who has worked on data-driven products in both academia and industry. My main goal is to improve the lives of others through my work.
  <br><br>
  I had the privilege of working on self-driving cars at Uber, NLP at Amazon, designing data features at startups, working on cutting-edge ML research, and many more. I'm always curious about new projects, so please feel free to reach out!
  <br><br>
  <a href="https://www.linkedin.com/in/94kazakov/" class="icon fa-linkedin">LinkedIn</a> 
  <a href="https://medium.com/@deniskazakov" class="icon fa-medium">Medium</a> 
  <a href="/pdf/DenisKazakov_resume.pdf" class="icon fa-file-text-o">Resume</a> 
  <a href="https://github.com/d-kz" class="icon fa-github">Github</a> 
  <a href="https://www.instagram.com/beauty_fondue/" class="icon fa-instagram">Instagram</a> 
  

is_project_page: false
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
