title: Denis Kazakov 
# overwrite https://aregsar.com/blog/2019/how-to-customize-your-github-pages-blog-layout-in-five-minutes/
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am an experienced data scientist who worked on a variety of data-driven products in both academia and industry. 
  <br><br>
  <br><br>

  I had the privilege of working on self-driving cars at Uber, natural language processing at Amazon, designing complex data features at startups, working on cutting-edge machine learning research with my advisor, and many more. My core strength is in understanding the problem from multiple perspectives and integrating that understanding into tangible deliverables. 


  My main goal is to improve lives of others through my work; and I sincerely believe in the power of technology and data intelligent systems to do so. I'm always open to new project, so please feel free to reach out. 
  <br><br>
  <a href="https://www.linkedin.com/in/94kazakov/">LinkedIn</a> 
  <a href="https://medium.com/@deniskazakov">Medium</a> 
  <a href="/pdf/DenisKazakov_resume.pdf">Resume</a> 
  <a href="https://github.com/d-kz">Github</a> 
  <a href="https://www.instagram.com/beauty_fondue/">Instagram</a> 
  
github:
  is_project_page: false
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

